(function(){
'use strict';
const C=FitCore,$=s=>document.querySelector(s),D=$('#device');
const names={chen:'陈阿姨',wang:'王叔叔',new:'新用户'};
let dataMobile=false,calendarOpen=false,requirementsOpen=false,adminPage='screen',milestoneReturn='home';
const labels={data:'我的数据',video:'视频屏保',image:'图片屏保',home:'设备首页',guide:'站位与身份确认',exercise:'运动进行中',report:'运动结果报告',milestones:'个人里程碑'};
const reviewPages=[['video','D01','视频屏保',4],['image','D02','图片屏保',3],['home','D03','设备首页',4],['calendar','D04','月度运动签到',3],['guide','—','站位与身份确认',0],['exercise','D05','运动进行中',3],['report','D06','运动结果报告',3],['data-screen','D07','大屏我的数据',4],['milestones','D08','个人里程碑',3],['data-mobile','M01','小程序我的数据',4]];
const requirementGroups=[
 {title:'交互大屏',code:'D',pages:[
  ['D01','视频屏保',['运动视频铺满 9:16 屏幕，运动名称和操作按钮覆盖在画面上。','单项体能完整演示 3 遍；AI 跟练随机播放 30 秒片段。','支持点击箭头或左右滑动浏览运动，并从“一键跟练”进入站位确认。','声音按钮只控制当前预览视频，不调整设备系统音量。']],
  ['D02','图片屏保',['客户可在管理后台配置最多 9 张图片。','图片按设定间隔自动轮播。','轻触图片屏保进入设备首页。']],
  ['D03','设备首页',['顶部用户区域提供运动签到入口。','签到入口区分“去签到”和“✓ 已签到”两种状态。','去签到固定进入舒缓热身操，已签到打开本月签到日历。','三个人群入口进入对应运动内容。']],
  ['D04','月度运动签到',['按自然月和周一至周日展示日期。','有效运动按上海时间自然日去重。','清楚区分已签到、今天和未来日期。']],
  ['D05','运动进行中',['开始运动后沿用站位阶段的 AI 跟练画面，并切换为计时和评分状态。','运动过程中支持提前结束；实际运动达到 10 秒后结束即按有效运动结算。','有效运动自动完成当日签到，运动记录归属于已确认的用户和项目。']],
  ['D06','运动结果报告',['展示本次成绩和简短累计进度。','有效运动自动完成当日签到。','天数按自然日累计，热量和时长按有效记录累计。']],
  ['D07','大屏我的数据',['累计运动卡片提供奖牌入口。','奖牌入口进入与 D08 共用的个人里程碑页面。','个人里程碑展示运动时长、消耗热量和运动天数三种升级进度。','大屏完成人脸确认后展示当前账号数据。']],
  ['D08','个人里程碑',['顶部并列展示运动时长、消耗热量和运动天数的当前奖牌状态。','每个维度展示当前累计、最佳奖牌和后续升级目标。','页面只保留左下侧返回入口，便于不同身高的用户操作。']]
 ]},
 {title:'管理后台',code:'B',pages:[
  ['B01','屏保管理',['沿用现有客户管理后台的页面结构和导航。','支持选择默认、排行榜、自定义图片或运动视频屏保。','运动视频可按目标人群智能推荐，也可指定内容并调整顺序。','课程素材和预览区间由平台维护，不在客户后台展示。']],
  ['B02','心率数据',['仅向配套采购心率设备的组织提供。','适用于用户与手环固定匹配的使用方式。','暂不支持多人共用同一手环。','有使用需求时联系服务该组织的销售同事。']]
 ]},
 {title:'小程序',code:'M',pages:[
  ['M01','我的数据',['展示当前登录账号的个人运动数据。','累计运动卡片进入与 D08 共用的个人里程碑页面。','个人里程碑展示三个累计维度的最佳奖牌和最近两个目标。','跑步与休闲锻炼未接入时显示空状态。']]
 ]}
];
const registered=new Set(['chen','wang']);
const storeKey='fitforall-review-v11';
let records=[];try{records=JSON.parse(localStorage.getItem(storeKey)||'[]');if(!Array.isArray(records))records=[]}catch{records=[]}
let milestoneDemo={};
let checkinDemo={};
let config=structuredClone(C.defaults),draft=structuredClone(config),screen='video',view='device',activePool=C.pool(config),idx=0,preview=null,previewTime=0,cycles=0,mediaEpoch=0,mediaFailed=new Set(),mediaURLs={},mediaLengths={},imageURLs=[],imageIndex=0,imageTime=0,muted=true;
let authMethod='face',authTimer,autoStartTimer;
let userId=null,intent='exercise',chosen=null,authState='idle',session=null,lastReport=null,elapsed=0,paused=false,dayOffset=0,sequence=0,idle=0,speed=1,feel=null,emptyOverride=false,logs=[],pendingSave=false;
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function now(){return Date.now()+dayOffset*86400000}function time(s){return `${Math.floor(s/60)}:${String(Math.floor(s%60)).padStart(2,'0')}`}function num(n){return Number(n.toFixed(1))}function toast(s){$('#toast').textContent=s;$('#toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').classList.remove('show'),3000)}
function log(s){logs.unshift(s);logs=logs.slice(0,3);updateInspector()}
function persist(){try{localStorage.setItem(storeKey,JSON.stringify(records))}catch{toast('当前浏览器无法保存本地数据，关闭页面后记录会丢失')}}
function displayTotals(id){const base=C.totals(records,id),override=milestoneDemo[id]||{};return {...base,days:Number.isFinite(override.days)?override.days:base.days,kcal:Number.isFinite(override.kcal)?override.kcal:base.kcal,seconds:Number.isFinite(override.minutes)?override.minutes*60:base.seconds}}
function changeMilestone(metric,step,zero=false){if(!userId)return;const current=displayTotals(userId),value=metric==='minutes'?current.seconds/60:current[metric];milestoneDemo[userId]={...(milestoneDemo[userId]||{}),[metric]:zero?0:num(value+step)};render();toast(`${metric==='minutes'?'实际运动分钟':metric==='kcal'?'消耗千卡':'运动天数'}已${zero?'归零':`增加 ${step}`}`)}
function coach(){return `<svg class="coach" viewBox="0 0 320 380" aria-label="动作演示占位插画"><defs><linearGradient id="shirt" x2="1" y2="1"><stop stop-color="#9dbce5"/><stop offset="1" stop-color="#648fc7"/></linearGradient></defs><ellipse cx="160" cy="353" rx="80" ry="12" fill="#b7cee6" opacity=".5"/><g class="body"><path d="M145 220L125 333Q130 346 146 337L165 249L180 338Q193 346 201 332L181 217" fill="#2d4466"/><path d="M123 115Q160 93 195 116L188 230Q158 240 132 228Z" fill="url(#shirt)"/><g class="arm-left"><path d="M136 126Q109 137 93 111L70 81" fill="none" stroke="#87a9d7" stroke-width="24" stroke-linecap="round"/><path d="M70 81L60 68" stroke="#e7bfa9" stroke-width="17" stroke-linecap="round"/></g><g class="arm-right"><path d="M184 126Q214 144 237 120L259 98" fill="none" stroke="#7599cc" stroke-width="24" stroke-linecap="round"/><path d="M259 98L269 86" stroke="#e7bfa9" stroke-width="17" stroke-linecap="round"/></g><rect x="151" y="83" width="19" height="29" rx="8" fill="#dfb39d"/><ellipse cx="160" cy="69" rx="29" ry="35" fill="#edc8b3"/><path d="M131 69Q121 21 164 27Q199 25 189 70L181 50Q156 61 139 48Z" fill="#4c576d"/><path d="M130 338L112 350Q111 359 145 354L147 339M180 339L178 351Q187 360 214 352L200 337" fill="#f8fbff"/><path d="M151 79Q160 86 169 79" fill="none" stroke="#b78072" stroke-width="2"/></g></svg>`}
function staticPreview(c){return `<div class="static-preview static-preview-${c.id}" role="img" aria-label="${c.name}静态色块占位"><i></i><i></i><i></i></div>`}
function top(right=''){return `<div class="device-top"><span aria-hidden="true"></span>${right||'<span>社区运动空间</span>'}</div>`}
function back(target='home'){return `<button class="back" data-go="${target}">‹ 返回</button>`}
function current(){return activePool[idx]}
function cleanMedia(){mediaEpoch++;const v=D.querySelector('video');if(v){v.pause();v.removeAttribute('src');v.load()}}
function navigate(next){calendarOpen=false;clearTimeout(authTimer);clearTimeout(autoStartTimer);cleanMedia();screen=next;idle=0;if(next==='home'){session=null;paused=false}if(next==='video'||next==='image'){userId=null;authState='idle';session=null;paused=false}if(next==='video'){emptyOverride=false;activePool=C.pool(config);idx=0;mediaFailed.clear();initPreview();return}if(next==='image'){imageTime=0;imageIndex=0}render()}
function initPreview(){cleanMedia();previewTime=0;cycles=0;if(!activePool.length){preview=null;render();return}const c=current();const range=config.ranges[c.id]||c.preview;try{preview=C.slice({...c,duration:mediaLengths[c.id]||c.duration},range)}catch{mediaFailed.add(c.id);nextItem(1);return}render()}
function nextItem(delta){if(!activePool.length)return;let n=0;do{idx=(idx+delta+activePool.length)%activePool.length;n++}while(mediaFailed.has(current().id)&&n<=activePool.length);if(n>activePool.length){activePool=[];preview=null;render();return}initPreview()}
function failMedia(){if(screen!=='video'||!current())return;log(`预览失败，跳过 ${current().name}`);mediaFailed.add(current().id);nextItem(1)}
function videoView(){const c=current();if(!c||emptyOverride)return `<div class="screen">${top('<span aria-hidden="true"></span>')}<div class="empty-state"><div class="big-icon">▤</div><h2>内容暂不可播放</h2><p>可以看看其他运动，<br>或稍后重新尝试。</p></div><button class="primary" data-go="home">看看其他运动</button><button class="secondary" id="retry-pool">重新尝试</button></div>`;return `<div class="screen immersive-video">${top('<span aria-hidden="true"></span>')}<div class="preview-heading"><h2>${c.name}</h2></div><div class="preview-card">${mediaURLs[c.id]?'<video id="preview-video" playsinline preload="auto"></video>':staticPreview(c)}<button class="sound" id="sound" aria-label="${muted?'开启':'关闭'}当前预览视频声音（不影响系统音量）" title="${muted?'开启':'关闭'}当前预览视频声音，不影响系统音量">${muted?'♪̸':'♪'}</button></div><div class="preview-bottom"><span id="preview-caption"></span><span id="preview-clock"></span></div><div class="preview-progress"><i id="preview-bar"></i></div><div class="switch-row"><button aria-label="上一个运动" id="previous" ${activePool.length<2?'disabled':''}>‹</button><button aria-label="下一个运动" id="next" ${activePool.length<2?'disabled':''}>›</button></div><div class="preview-actions"><button class="primary" id="start-preview" aria-label="一键跟练${c.name}">一键跟练</button><button class="secondary" data-go="home">看看其他运动</button></div></div>`}
function imageView(){const sources=config.images.length?config.images:['./assets/screensaver-fun-ai.jpg'],active=imageIndex%sources.length;return `<div class="screen image-screen" id="image-background"><img class="image-screensaver-poster" src="${sources[active]}" alt="趣味化 AI 体育锻炼图片屏保" draggable="false">${sources.length>1?`<div class="dots">${sources.map((_,i)=>`<i class="${i===active?'active':''}"></i>`).join('')}</div>`:''}</div>`}
function checkinKey(){return `${userId||'none'}:${C.day(now())}`}
function todayChecked(){if(!userId)return false;const key=checkinKey();return Object.hasOwn(checkinDemo,key)?checkinDemo[key]:records.some(r=>r.userId===userId&&C.day(r.timestamp)===C.day(now()))}
function setCheckinState(checked){if(!userId)return;checkinDemo[checkinKey()]=checked;log(`签到状态切换为${checked?'已签到':'未签到'}（模拟）`);render();toast(`已切换为${checked?'已签到':'未签到'}状态`)}
function homeView(){const checked=todayChecked();return `<div class="screen reference-home review-highlight"><img class="home-original" src="../../v1.0-home.png" alt="v1.0 首页原图：场地信息、三个人群入口、体态检测、健康百科、趣味锻炼、边看边学、排行榜" draggable="false"><button id="home-data" class="home-hotspot hotspot-profile" aria-label="我的数据"></button><button id="checkin" class="checkin-annotation review-new-feature ${checked?'is-checked':'is-unchecked'}" aria-label="${checked?'今日已签到，查看本月签到日历':'去签到，完成热身点亮今天'}">${checked?'✓ 已签到':'去签到'}</button><button class="home-hotspot hotspot-adult" data-audience="adult" aria-label="热力健将"></button><button class="home-hotspot hotspot-youth" data-audience="youth" aria-label="跃动少年"></button><button class="home-hotspot hotspot-senior" data-audience="senior" aria-label="康乐银发"></button>${calendarOpen?calendarView():''}</div>`}
function choose(id,origin='exercise'){chosen=C.catalog.find(c=>c.id===id);intent=origin;userId=null;authState='idle';navigate('guide');scheduleFace();log(`进入站位：${chosen?.name||(intent==='data'?'查看我的数据':'查看里程碑')}`)}
function calendarView(){const today=C.day(now()),[year,month]=today.split('-').map(Number);const count=new Date(Date.UTC(year,month,0)).getUTCDate(),offset=(new Date(Date.UTC(year,month-1,1)).getUTCDay()+6)%7;const prefix=today.slice(0,7),days=new Set(records.filter(r=>r.userId===userId).map(r=>C.day(r.timestamp)).filter(d=>d.startsWith(prefix)));if(todayChecked())days.add(today);else days.delete(today);return `<div class="medal-backdrop"><section class="medal-dialog checkin-calendar" role="dialog" aria-modal="true" aria-labelledby="calendar-title"><header><h2 id="calendar-title">本月运动签到</h2><button id="close-calendar" aria-label="关闭签到日历">×</button></header><div class="calendar-month">${year} 年 ${month} 月</div><div class="calendar-total">本月已签到 <b>${days.size}</b> 天</div><div class="calendar-week">${['一','二','三','四','五','六','日'].map(d=>'<span>'+d+'</span>').join('')}</div><div class="calendar-grid">${Array.from({length:offset},()=>'<span aria-hidden="true"></span>').join('')}${Array.from({length:count},(_,i)=>{const n=i+1,date=prefix+'-'+String(n).padStart(2,'0'),done=days.has(date),isToday=date===today;return `<div class="calendar-day ${done?'signed':''} ${isToday?'is-today':''} ${date>today?'future':''}" aria-label="${month}月${n}日${isToday?'，今天':''}，${done?'已签到':date>today?'未到日期':'未签到'}" ${isToday?'aria-current="date"':''}><b>${n}</b><small>${done?'✓':isToday?'今天':''}</small></div>`}).join('')}</div><div class="calendar-legend"><span>✓ 已签到</span><span><i></i> 今天</span></div><p class="calendar-note">完成一次运动，点亮当天</p></section></div>`}
function checkin(){if(todayChecked()){calendarOpen=true;render();D.querySelector('#close-calendar').focus();return}const warmup=C.catalog.find(c=>c.id==='warm');if(!warmup){toast('舒缓热身操暂不可用，请稍后重试');return}choose(warmup.id,'checkin')}
function scheduleFace(){clearTimeout(authTimer);userId=null;authState='idle';render();authTimer=setTimeout(()=>{if(screen==='guide')authenticate('face')},1000)}
function authenticate(method='face'){authMethod=method;if(method==='face'&&$('#identity').value==='failure'){authState='failed';render();log('人脸确认失败，等待调整站位后重新识别');return}if(!registered.has($('#person').value)&&authState!=='register-ready'){authState='new';render();return}userId=$('#person').value;registered.add(userId);authState='confirmed';render();log(`${method==='wechat'?'微信':'人脸'}确认：${names[userId]}`);autoStartTimer=setTimeout(()=>{if(screen==='guide'&&authState==='confirmed')startExercise()},900)}
function guideView(){const confirmed=authState==='confirmed';const checked=confirmed&&records.some(r=>r.userId===userId&&C.day(r.timestamp)===C.day(now()));let title=['milestones','data'].includes(intent)?'确认身份，查看积累':'请站在运动区域';let text='面向屏幕，让全身进入画面';let identity=`<strong>正在识别人脸，请看向摄像头</strong><p>站位时确认身份，运动记录会保存到你的账号。</p>`;let actions='';
if(authState==='failed'){identity='<strong>暂时没有识别成功</strong><p>请调整站位并看向摄像头，等待重新识别。</p>';actions=''}
if(authState==='new'){identity='<strong>欢迎第一次来运动</strong><p>继续完成现有注册与说明确认流程。</p><label class="confirm-check"><input type="checkbox" id="registration">已完成注册说明确认（演示）</label>';actions='<button class="primary" id="register" disabled>完成注册并继续</button>'}
if(confirmed){identity=`<strong>${names[userId]}，身份已确认</strong><p>${['data','milestones'].includes(intent)?'正在打开你的运动数据':checked?'今天已签到，即将开始运动':intent==='checkin'?'即将开始热身，完成后点亮今天':'已站好，即将开始运动'}</p>`;actions=''}
if(['milestones','data'].includes(intent))return `<div class="screen"><div class="back-row">${back()}</div><h2 class="page-title">${title}</h2><div class="guide-frame">${coach()}</div><div class="identity-card">${identity}</div>${actions}</div>`;
const ai=chosen?.type==='ai';return `<div class="screen preparation ${ai?'preparation-ai':'preparation-single'}">${ai?`<div class="teacher-preview"><h2>预备式</h2>${coach()}<span>教练示范 · 占位</span></div>`:''}<div class="camera-preview"><div class="camera-room"></div>${coach()}<div class="standing-zone"></div><div class="camera-hud"><div class="identity-pill"><span class="profile-dot">${confirmed?names[userId][0]:'人'}</span><div>${confirmed?names[userId]:'正在确认身份'}${!ai?`<small>${chosen.name}</small>`:''}</div></div><div class="score-pill">${!ai?`<span>${time(chosen.duration)}</span>`:''}<b>0</b>${ai?'<small>AI 打分</small>':''}</div></div><div class="position-hint">${confirmed?'身份已确认 · 请站好':'请站入绿色区域，看向摄像头'}</div><span class="camera-mock">摄像头画面示意</span></div><div class="preparation-auth"><div class="identity-card">${identity}</div><div class="preparation-actions">${actions}</div></div><div class="preparation-back">${back()}</div></div>`}
function startExercise(){if(!userId)return;if(intent==='data'){navigate('data');return}if(intent==='milestones'){milestoneReturn='home';navigate('milestones');return}session={id:`${Date.now()}-${++sequence}-${Math.random().toString(36).slice(2)}`,userId,courseId:chosen.id,type:chosen.type,intent};elapsed=0;paused=false;navigate('exercise');log(`本次运动绑定 ${names[userId]} / ${chosen.name}`)}
function exerciseView(){return `<div class="screen preparation exercise-active"><div class="teacher-preview"><h2>${chosen.name}</h2>${coach()}<span>教练示范</span></div><div class="camera-preview"><div class="camera-room"></div>${coach()}<div class="standing-zone"></div><div class="camera-hud"><div class="identity-pill"><span class="profile-dot">${names[session.userId][0]}</span><div>${names[session.userId]}<small>${chosen.name}</small></div></div><div class="score-pill"><span id="exercise-clock"></span><b id="exercise-score">0</b><small>AI 打分</small></div></div><div class="position-hint">AI 跟练进行中</div><div class="exercise-camera-progress"><i id="exercise-bar"></i></div><span class="camera-mock">摄像头画面示意</span></div></div>`}
function finish(reason){if(!session||screen!=='exercise')return;const seconds=reason==='normal'?chosen.duration:Number(elapsed.toFixed(3));const record={...session,seconds,kcal:num(chosen.kcal*seconds/chosen.duration),reason,timestamp:now()};const before=C.totals(records,record.userId);const had=records.some(r=>r.userId===record.userId&&C.day(r.timestamp)===C.day(record.timestamp));const result=C.settle(records,record,config.threshold);records=result.records;persist();lastReport={record,valid:result.valid,newCheckin:result.added&&!had,before,after:C.totals(records,record.userId)};feel=null;userId=record.userId;navigate('report');log(result.valid?'有效运动已结算；重复打开报告不再累计':'提前结束未达门槛，本次未计入')}
function progressCard(){const t=C.totals(records,userId);const checked=records.some(r=>r.userId===userId&&C.day(r.timestamp)===C.day(now()));const next=C.progress(t.days,C.levels.days);let note=next.next?`再运动 ${next.remaining} 天，解锁 ${next.next} 天里程碑`:'运动天数本阶段已完成，继续积累';if(lastReport?.valid){const b=lastReport.before,a=lastReport.after;const earned=C.levels.days.some(n=>b.days<n&&a.days>=n)||C.levels.kcal.some(n=>b.kcal<n&&a.kcal>=n)||C.levels.minutes.some(n=>b.seconds/60<n&&a.seconds/60>=n);if(earned)note='✦ 本次达成新里程碑，去看看你的积累'}return `<div class="growth-card"><div class="growth-head">${checked?'✓ 今日已签到':'今日尚未签到'}<span>${lastReport?.newCheckin&&lastReport.valid?'本次点亮今天':'签到与成长'}</span></div><div class="growth-metrics"><span><b>${t.days}</b>天</span><span><b>${num(t.kcal)}</b>千卡</span><span><b>${num(t.seconds/60)}</b>分钟</span></div><div class="growth-note">${note}</div><button class="growth-link" id="report-milestones">查看我的里程碑 →</button></div>`}
function metrics(r){return `<div class="metric-card"><div class="metric"><b>${r.type==='single'?Math.floor(r.seconds*1.5):num(r.kcal)}<small>${r.type==='single'?'次':'千卡'}</small></b><span>${r.type==='single'?'运动成绩':'运动消耗'}</span></div><div class="metric"><b>${r.type==='single'?num(r.kcal):time(r.seconds)}<small>${r.type==='single'?'千卡':''}</small></b><span>${r.type==='single'?'运动消耗':'运动时长'}</span></div><div class="metric"><b>${r.type==='single'?r.seconds:Math.floor(r.seconds/30)}<small>${r.type==='single'?'秒':'组'}</small></b><span>${r.type==='single'?'运动耗时':'完成动作'}</span></div></div>`}
function reportView(){if(!lastReport)return '<div class="screen"><h2>还没有运动报告</h2><button class="primary" data-go="home">返回首页</button></div>';const r=lastReport.record,c=C.catalog.find(c=>c.id===r.courseId);return `<div class="screen report review-highlight"><div class="report-head"><span class="avatar">${names[r.userId][0]}</span><span>${names[r.userId]}</span><b>${c.name}</b></div>${r.type==='single'?metrics(r):`<div class="ai-score"><span style="color:#e4a45c;font-size:16px">运动评分</span><b>${Math.min(95,Math.floor(r.seconds/c.duration*85))}</b><div class="stars">★ ★ ☆</div>${metrics(r)}</div>`}${!lastReport.valid?'<div class="invalid-note">本次未计入签到与累计进度<br><small>提前结束，未达到有效运动时长</small></div>':''}<div class="review-new-feature">${progressCard()}</div>${r.type==='single'?`<div class="chart-card"><div class="chart-title">运动曲线 <small>演示数据</small></div><svg viewBox="0 0 420 90"><path d="M0 20H420M0 50H420M0 80H420" stroke="#edf2f9"/><path d="M5 62Q55 20 105 36T205 52T305 32T415 38" fill="none" stroke="#4a83ef" stroke-width="4"/></svg></div><div class="chart-card" style="padding-bottom:28px"><div class="chart-title">近期成绩 <small>演示数据</small></div><div class="bar-chart">${[60,40,30,48,67].map((h,i)=>`<i style="height:${h}px" data-label="09/${i+1}"></i>`).join('')}</div></div>`:''}<div class="feeling"><span id="feeling-label">这次运动，感觉怎么样？</span><div class="feeling-buttons">${['轻松','稍累','累','很累','超累'].map((f,i)=>`<button data-feel="${i}" class="${feel===i?'selected':''}">${f}</button>`).join('')}</div></div><div class="report-actions"><button data-go="home">返回首页</button><button id="again">再来一次</button></div></div>`}
function milestoneView(){const t=displayTotals(userId),returnLabel=milestoneReturn==='data'?'返回我的数据':milestoneReturn==='report'?'返回运动报告':'返回首页',metrics=[['运动时长',num(t.seconds/60),'分钟',C.levels.minutes],['消耗热量',num(t.kcal),'千卡',C.levels.kcal],['运动天数',t.days,'天',C.levels.days]];return `<div class="screen milestone"><div class="milestone-heading"><h2>我的里程碑</h2><p>${names[userId]||'我的'} · 每一步，都算数</p></div><div class="milestone-medals">${metrics.map(([title,val,unit,steps])=>{const reached=steps.filter(n=>n<=val),best=reached.at(-1)||0,rank=reached.length;return `<div class="milestone-medal-state ${best?'earned':'pending'}"><div class="milestone-medal-art tier-${Math.min(rank,3)}">${medalIcon()}</div><small>${title}</small><strong>${best?best+' '+unit:'待点亮'}</strong></div>`}).join('')}</div>${metrics.map(([title,val,unit,steps])=>{const p=C.progress(val,steps);return `<div class="milestone-card"><h3>${title}<span>${val} ${unit}</span></h3><div class="milestone-track"><i style="width:${p.ratio*100}%"></i></div><div class="levels">${steps.map(n=>`<span class="${val>=n?'earned':''}">${val>=n?'✓ ':''}${n}</span>`).join('')}</div><p>${p.next?`距离 ${p.next} ${unit}，还差 ${num(p.remaining)} ${unit}`:'本阶段已完成，继续积累'}</p></div>`}).join('')}<p class="milestone-footer">休息几天也没关系，已有积累不会清零</p><button class="milestone-return" data-go="${milestoneReturn}">‹ ${returnLabel}</button></div>`}
function medalIcon(){return `<svg viewBox="0 0 48 56" aria-hidden="true"><path d="M10 1h11l7 22-11 5z" fill="#ff9a38"/><path d="M27 1h11L31 28l-11-5z" fill="#ffbe54"/><circle cx="24" cy="34" r="19" fill="#ffe3a1" stroke="#eab34a" stroke-width="2"/><path d="m24 21 4 8 9 1-7 6 2 9-8-5-8 5 2-9-7-6 9-1z" fill="#dc9a2e"/></svg>`}
function dataView(){const t=displayTotals(userId);const today=records.filter(r=>r.userId===userId&&C.day(r.timestamp)===C.day(now()));const mins=rs=>num(rs.reduce((n,r)=>n+r.seconds,0)/60);const mine=records.filter(r=>r.userId===userId);return `<div class="screen personal-data review-highlight ${dataMobile?'mobile-data':''}"><h2 class="data-place">上海三邻桥社区公园</h2><div class="data-user"><span class="data-avatar">${names[userId]?.[0]||'人'}</span><div><h2>${names[userId]||'我的数据'}</h2><p>UID ${userId==='chen'?'19******36':userId==='wang'?'19******28':'新用户'}</p></div>${!dataMobile?'<div class="data-qr"><span>▦</span><small>微信扫码<br>手机查看详情</small></div>':''}</div><div class="data-grid"><div class="data-card"><h3>今日运动</h3><div class="data-value">${mins(today)}<small>分钟</small></div><p>共消耗 <b>${num(today.reduce((n,r)=>n+r.kcal,0))}</b> 千卡</p></div><div class="data-card"><h3>累计运动</h3><button id="open-medals" class="medal-entry review-new-feature" aria-label="查看运动里程碑">${medalIcon()}</button><div class="data-value">${num(t.seconds/60)}<small>分钟</small></div><p>共消耗 <b>${num(t.kcal)}</b> 千卡</p></div>${dataMobile?'<div class="data-running"><h3>累计跑步 <span>— 公里</span></h3><p>最近一周</p><div class="running-empty">暂无跑步记录</div><div class="week-labels">周一　周二　周三　周四　今天　周六　周日</div></div>':''}<div class="data-card category physical"><h3>体能训练</h3><div class="data-value">${mins(mine.filter(r=>r.type==='single'))}<small>分钟</small></div></div><div class="data-card category leisure"><h3>休闲锻炼</h3><div class="data-value">—<small>分钟</small></div></div></div>${dataMobile?'<div class="data-tabs"><b>♙<span>我的数据</span></b><span>▤<small>运动记录</small></span></div>':'<div class="data-exit"><button class="secondary" id="logout">退出登录</button><p>60 秒未进行操作自动退出</p></div><div class="data-back">'+back()+'</div>'}</div>`}
function render(){cleanMedia();D.innerHTML=({data:dataView,video:videoView,image:imageView,home:homeView,guide:guideView,exercise:exerciseView,report:reportView,milestones:milestoneView}[screen])();$('#screen-label').textContent=screen==='data'?(dataMobile?'小程序 · 我的数据':'大屏 · 我的数据'):labels[screen];bindDevice();if(screen==='video')attachVideo();updateDynamic();updateInspector();updateRequirementsNote();resize()}
function bindDevice(){D.querySelectorAll('.goal-rail').forEach(rail=>{let drag=null;rail.onpointerdown=e=>{if(e.pointerType!=='mouse'||e.button!==0)return;drag={x:e.clientX,left:rail.scrollLeft};rail.setPointerCapture(e.pointerId)};rail.onpointermove=e=>{if(!drag)return;rail.scrollLeft=drag.left+(drag.x-e.clientX)*rail.clientWidth/rail.getBoundingClientRect().width};rail.onpointerup=rail.onpointercancel=()=>drag=null;rail.onlostpointercapture=()=>drag=null});D.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>{if(b.dataset.go==='report'){userId=lastReport.record.userId}navigate(b.dataset.go)});const on=(id,fn)=>{const e=D.querySelector('#'+id);if(e)e.onclick=fn};on('close-calendar',()=>{calendarOpen=false;render();D.querySelector('#checkin').focus()});on('logout',()=>{userId=null;authState='idle';navigate('home')});on('open-medals',()=>{milestoneReturn='data';navigate('milestones')});on('previous',()=>nextItem(-1));on('next',()=>nextItem(1));on('retry-pool',()=>navigate('video'));on('start-preview',()=>{const id=current()?.id;if(id)choose(id)});on('sound',()=>{muted=!muted;const v=D.querySelector('video');if(v)v.muted=muted;D.querySelector('#sound').textContent=muted?'♪̸':'♪';D.querySelector('#sound').setAttribute('aria-label',`${muted?'开启':'关闭'}当前预览视频声音（不影响系统音量）`);D.querySelector('#sound').title=`${muted?'开启':'关闭'}当前预览视频声音，不影响系统音量`;if(!v)toast('当前为静态示意；导入视频后，此按钮仅控制当前预览声音')});on('checkin',checkin);on('home-data',()=>{dataMobile=false;choose(null,'data')});D.querySelectorAll('[data-course]').forEach(b=>b.onclick=()=>choose(b.dataset.course));D.querySelectorAll('[data-audience]').forEach(b=>b.onclick=()=>{cleanMedia();screen='video';activePool=C.catalog.filter(c=>c.audiences.includes(b.dataset.audience));idx=0;mediaFailed.clear();initPreview();log('按所选人群浏览运动内容')});on('view-milestones',()=>choose(null,'milestones'));const check=D.querySelector('#registration');if(check)check.onchange=()=>D.querySelector('#register').disabled=!check.checked;on('register',()=>{if(!check?.checked)return;authState='register-ready';authenticate(authMethod)});on('ready',startExercise);on('pause',()=>{paused=!paused;D.querySelector('#pause').textContent=paused?'继续运动':'暂停一下';updateInspector()});on('end-exercise',()=>finish('early'));on('report-milestones',()=>{milestoneReturn='report';navigate('milestones')});on('again',()=>choose(lastReport.record.courseId));D.querySelectorAll('[data-feel]').forEach(b=>b.onclick=()=>{feel=+b.dataset.feel;D.querySelectorAll('[data-feel]').forEach(x=>x.classList.toggle('selected',x===b));D.querySelector('#feeling-label').textContent=['很轻松，今天动得不错','稍微有点累，休息一下吧','辛苦了，按自己的节奏来','先休息一下吧','今天先到这里，休息一下吧'][feel]});on('image-background',e=>{if(e.target.closest('button'))return;navigate('home')})}
function attachVideo(){const v=D.querySelector('#preview-video'),c=current(),epoch=mediaEpoch;if(!v||!c)return;v.muted=muted;v.src=mediaURLs[c.id];let start=preview.start,initialized=false;const timeout=setTimeout(()=>{if(epoch===mediaEpoch&&!initialized)failMedia()},12000);v.onloadedmetadata=()=>{clearTimeout(timeout);if(epoch!==mediaEpoch)return;if(c.type==='single'){preview={start:0,end:v.duration,repeats:3}}else if(preview.end>v.duration){failMedia();return}v.currentTime=preview.start;v.playbackRate=Math.min(16,speed);initialized=true;v.play().catch(()=>toast('点击演示画面播放视频'));};v.onclick=()=>v.play().catch(()=>toast('视频无法播放，请更换素材'));v.onerror=()=>{clearTimeout(timeout);if(epoch===mediaEpoch)failMedia()};v.ontimeupdate=()=>{if(epoch!==mediaEpoch||!initialized)return;previewTime=Math.max(0,v.currentTime-preview.start);updateDynamic();if(c.type==='ai'&&v.currentTime>=preview.end)nextItem(1)};v.onended=()=>{if(epoch!==mediaEpoch)return;if(c.type==='ai'){nextItem(1);return}cycles++;if(cycles>=3){nextItem(1)}else{previewTime=0;v.currentTime=0;v.play().catch(()=>{})}}}
function tick(dt,manual=false){if(view!=='device'||(document.hidden&&!manual))return;if(screen==='video'&&preview&&current()){const video=D.querySelector('video');if(video){if(manual){video.currentTime=Math.min(preview.end,video.currentTime+dt)}return}previewTime+=dt;const len=preview.end-preview.start;if(previewTime>=len){previewTime=0;cycles++;if(cycles>=preview.repeats){nextItem(1);return}}}if(screen==='image'){imageTime+=dt;if(imageTime>=config.imageInterval){imageTime=0;imageIndex=(imageIndex+1)%(config.images.length||1);render()}}if(screen==='exercise'&&!paused){elapsed=Math.min(chosen.duration,elapsed+dt);if(elapsed>=chosen.duration){finish('normal');return}}updateDynamic()}
function updateDynamic(){if(screen==='video'&&preview&&current()){const len=preview.end-preview.start;const el=D.querySelector('#preview-caption');if(el)el.textContent=current().type==='single'?`演示 ${Math.min(cycles+1,3)} / 3 遍`:'30 秒精选片段';const clock=D.querySelector('#preview-clock');if(clock)clock.textContent=`${time(previewTime)} / ${time(len)}`;const bar=D.querySelector('#preview-bar');if(bar)bar.style.width=`${Math.min(100,previewTime/len*100)}%`}if(screen==='exercise'){D.querySelector('#exercise-clock').textContent=time(chosen.duration-elapsed);D.querySelector('#exercise-score').textContent=Math.min(95,Math.floor(elapsed/chosen.duration*85));D.querySelector('#exercise-bar').style.width=elapsed/chosen.duration*100+'%'}}
function reviewPageKey(){if(screen==='home'&&calendarOpen)return 'calendar';if(screen==='data')return dataMobile?'data-mobile':'data-screen';return screen}
function openReviewPage(key){const selected=$('#person')?.value||'chen',course=C.catalog.find(c=>c.id==='baduan')||C.catalog.find(c=>c.type==='ai')||C.catalog[0];clearTimeout(authTimer);logs=[];if(key==='video'||key==='image'){navigate(key);return}if(key==='home'){userId=selected;navigate('home');return}if(key==='calendar'){userId=selected;navigate('home');calendarOpen=true;render();return}if(key==='guide'){choose(course.id);return}if(key==='exercise'){chosen=course;userId=selected;registered.add(userId);session={id:`review-exercise-${Date.now()}`,userId,courseId:course.id,type:course.type,intent:'exercise'};elapsed=0;paused=false;navigate('exercise');return}if(key==='report'){chosen=course;userId=selected;registered.add(userId);const record={id:`review-report-${Date.now()}`,userId,courseId:course.id,type:course.type,intent:'exercise',seconds:course.duration,kcal:course.kcal,reason:'normal',timestamp:now()},totals=C.totals(records,userId);lastReport={record,valid:true,newCheckin:false,before:totals,after:totals};navigate('report');return}if(key==='data-screen'||key==='data-mobile'){dataMobile=key==='data-mobile';userId=selected;navigate('data');return}if(key==='milestones'){userId=selected;milestoneReturn='home';navigate('milestones')}}
function updateInspector(){const key=reviewPageKey(),meta=reviewPages.find(([id])=>id===key)||[key,'',labels[screen],0],c=current(),requirements=currentRequirements();$('#inspector-current-title').textContent=`${meta[1]} ${meta[2]}`;$('#inspector-change-count').textContent=`${meta[3]} 项变动`;$('#inspector-requirements-list').innerHTML=requirements.items.map(item=>`<li>${esc(item)}</li>`).join('');const checked=todayChecked();$('#checkin-unchecked')?.classList.toggle('active',!checked);$('#checkin-checked')?.classList.toggle('active',checked);document.querySelectorAll('[data-review-page]').forEach(b=>b.classList.toggle('active',b.dataset.reviewPage===key));document.querySelectorAll('.inspector [data-pages]').forEach(el=>el.classList.toggle('hidden',!el.dataset.pages.split(/\s+/).includes(key)));const notes={video:'仅显示预览速度、视频失败与空内容池控制。',image:'本页没有额外模拟参数，直接检查图片和轻触进入首页。',home:'可切换用户查看未签到／已签到状态。',calendar:'可切换用户或模拟下一天，检查本月签到分布。',guide:'可切换用户与人脸确认结果。',exercise:'可调整速度、推进时间或提前结束。',report:'可模拟下一天或重放同一报告，检查累计幂等。','data-screen':'可切换用户或模拟下一天，检查大屏个人数据。','data-mobile':'可切换用户或模拟下一天，检查小程序个人数据。',milestones:'可切换用户或模拟下一天，检查三个累计维度。'};$('#page-assumption-text').textContent=notes[key]||'';let detail=`${meta[2]} · ${C.day(now())}`;if(screen==='video'&&c&&preview)detail+=`<br>${c.name} · ${c.type==='single'?'完整播放 3 遍':`片段 ${time(preview.start)}—${time(preview.end)}`}`;if(screen==='data')detail+='<br>奖牌入口连接运动天数、热量和时长三种里程碑。';if(screen==='home')detail+=calendarOpen?'<br>展示当前用户本月有效运动签到。':'<br>签到入口区分未签到与已签到状态。';if(screen==='guide')detail+=`<br>身份：${userId?names[userId]:'尚未确认'} · ${intent==='checkin'?'热身签到':intent==='milestones'?'查看记录':'直接运动'}`;if(screen==='exercise'&&session)detail+=`<br>绑定 ${names[session.userId]} · ${paused?'暂停':'计时中'}`;if(screen==='report'&&lastReport)detail+=`<br>${lastReport.valid?'有效':'未计入'} · ${lastReport.record.seconds} 秒 · ${lastReport.record.kcal} 千卡`;$('#state-detail').innerHTML=detail;$('#event-log').innerHTML=logs.map(l=>`<div>· ${esc(l)}</div>`).join('')}
function currentRequirements(){if(screen==='video')return {title:'视频屏保',items:['运动预览视频铺满 9:16 屏幕，运动名称与操作按钮浮在画面上。','单项体能完整演示 3 遍后自动播放下一项；AI 跟练播放随机 30 秒片段后自动播放下一项。','点击两侧箭头或左右滑动浏览内容；点击“一键跟练”进入站位与身份确认。','声音按钮切换当前预览视频的声音，不调整设备系统音量。']};if(screen==='image')return {title:'图片屏保',items:['管理后台可配置最多 9 张屏保图片。','图片按设定间隔自动轮播。','轻触屏保画面进入设备首页。']};if(screen==='home'&&calendarOpen)return {title:'月度运动签到',items:['展示当前月份，并按周一至周日排列日期。','有效运动按上海时间自然日去重，区分已签到、今天和未来日期。','日期用于查看签到状态，关闭弹窗后返回设备首页。']};if(screen==='home')return {title:'设备首页',items:['顶部用户区域提供运动签到入口。','今日未签到显示“去签到”，完成签到后显示“✓ 已签到”。','点击“去签到”固定进入舒缓热身操；点击“✓ 已签到”查看本月签到日历。','三个人群卡片分别进入对应人群的运动内容。']};if(screen==='guide')return {title:'站位与身份确认',items:['进入运动前先引导用户站入绿色区域，并自动进行人脸确认。','已注册用户完成登录；新用户完成注册后继续。','身份确认后，将当前用户与本次运动记录绑定。','云端人脸服务不可用时，本地采集人脸并保存本次运动会话，联网后自动补传。']};if(screen==='exercise')return {title:'运动进行中',items:['开始运动后沿用站位阶段的 AI 跟练画面，并切换为计时和评分状态。','运动过程中支持提前结束；实际运动达到 10 秒后结束即按有效运动结算。','有效运动自动完成当日签到，运动记录归属于站位阶段确认的用户和运动项目。']};if(screen==='report')return {title:chosen?.type==='ai'?'AI 跟练报告':'单项体能报告',items:['结果报告展示本次成绩，并增加统一的简短进度卡。','有效运动自动完成当日签到。','运动天数按自然日累计，热量和运动时长按有效记录累计。']};if(screen==='data')return {title:dataMobile?'小程序 · 我的数据':'大屏 · 我的数据',items:['“累计运动”卡片右上角提供奖牌入口。','奖牌入口进入与 D08 共用的个人里程碑页面。','个人里程碑统一展示三个累计维度的升级进度。',dataMobile?'小程序展示当前已登录账号的个人数据。':'大屏完成人脸确认后展示当前账号的个人数据。']};return {title:'个人里程碑',items:['顶部并列展示三个维度的当前奖牌状态。','每个维度展示当前累计、最佳奖牌和后续升级目标。','页面只保留左下侧返回入口，便于不同身高的用户操作。']}}
function updateRequirementsNote(){if(!requirementsOpen)return;const content=currentRequirements();$('#context-requirements-title').textContent=content.title;$('#context-requirements-list').innerHTML=content.items.map(item=>`<li>${esc(item)}</li>`).join('')}
function toggleRequirements(open){requirementsOpen=open;const area=$('.stage-area'),button=$('#open-requirements'),panel=$('#context-requirements');area.classList.toggle('requirements-open',open);button.setAttribute('aria-expanded',String(open));panel.setAttribute('aria-hidden',String(!open));button.textContent=open?'收起本页需求':'查看本页需求';if(open)updateRequirementsNote();setTimeout(resize,0)}
function showView(next){if(next!=='device'&&requirementsOpen)toggleRequirements(false);view=next;document.body.classList.remove('legacy-admin-open');const navView=next==='admin'?'device':next;document.querySelectorAll('.nav').forEach(b=>b.classList.toggle('active',b.dataset.view===navView));if(next!=='device')document.querySelectorAll('[data-review-page]').forEach(b=>b.classList.remove('active'));document.querySelectorAll('[data-admin-page]').forEach(b=>b.classList.toggle('active',next==='admin'&&b.dataset.adminPage===adminPage));['device','admin','spec','docs'].forEach(v=>$('#'+v+'-view').classList.toggle('hidden',v!==next));$('#view-title').textContent={device:'从看见，到动起来',admin:'让合适的内容，出现在合适的场地',spec:'先看说明，再走流程',docs:'按终端查看本轮需求'}[next];if(next==='admin'){draft=structuredClone(config);renderExistingAdmin()}if(next==='spec')renderSpec();if(next==='docs')renderDocs();if(next==='device'){render();idle=0}const video=D.querySelector('video');if(video){if(next==='device')video.play().catch(()=>{});else video.pause()}resize()}
function renderExistingAdmin(){
 if(adminPage==='heart'){
  $('#admin-view').innerHTML=`<div class="legacy-admin-shell">
   <header class="legacy-admin-top"><div class="legacy-venue"><span class="legacy-home-icon">⌂</span><b>徐汇区新时代文明实践中心</b></div><div class="legacy-greeting">下午好，徐汇区新时代文明实践中心 <span class="legacy-menu">☰</span></div></header>
   <aside class="legacy-admin-side"><nav>
    <button><i class="legacy-icon blue">♙</i><span>数据统计</span><em>⌄</em></button>
    <button class="selected" data-admin-section="heart"><i class="legacy-icon red">♥</i><span>心率数据</span><em>⌄</em></button>
    <button><i class="legacy-icon amber">▤</i><span>运动视频</span></button>
    <button><i class="legacy-icon green">◧</i><span>用户管理</span></button>
    <button><i class="legacy-icon mint">♙</i><span>账号管理</span></button>
    <button><i class="legacy-icon yellow">▣</i><span>我的账号</span></button>
    <button data-admin-section="screen"><i class="legacy-icon purple">▰</i><span>屏保管理</span></button>
   </nav></aside>
   <main class="legacy-admin-main"><div class="legacy-page-heading"><h1>心率数据</h1><button id="leave-admin">返回产品评审</button></div>
    <section class="heart-empty-card" aria-labelledby="heart-empty-title">
     <div class="heart-device-art" aria-hidden="true"><span class="heart-watch"><i>♥</i></span><span class="heart-pulse"></span></div>
     <span class="heart-device-tag">需配套心率设备</span>
     <h2 id="heart-empty-title">暂无心率数据</h2>
     <p class="heart-empty-lead">本功能仅供已配套采购心率设备的组织使用。</p>
     <div class="heart-use-grid">
      <div><span class="heart-use-icon supported">✓</span><section><b>适用场景</b><p>一位用户与一只手环固定匹配使用。</p></section></div>
      <div><span class="heart-use-icon unsupported">!</span><section><b>暂不支持</b><p>多位用户共用同一只手环。</p></section></div>
     </div>
     <div class="heart-sales-note"><span>i</span><p>如需开通或了解配套方案，请联系服务您的销售同事。</p></div>
    </section>
   </main>
  </div>`;
  mountAdminReview();
  bindExistingAdmin();
  return;
 }
 const selectableCatalog=C.catalog.filter(c=>c.screen!==false),order=[...draft.fixed,...selectableCatalog.map(c=>c.id).filter(id=>!draft.fixed.includes(id))],isVideo=draft.mode==='video';
 const poolItems=(draft.poolMode==='fixed'?order.map(id=>C.catalog.find(c=>c.id===id)):C.pool(draft));
 const contentRule='体能完整演示 3 遍后切换；AI 跟练播放 30 秒精选片段。';
 const fixedContentRows=poolItems.map(c=>`<div class="legacy-content-row"><input aria-label="选择${c.name}" type="checkbox" data-legacy-pool="${c.id}" ${draft.fixed.includes(c.id)?'checked':''}><div><b>${c.name}</b></div>${draft.fixed.includes(c.id)?`<span class="legacy-order"><button aria-label="上移${c.name}" data-legacy-up="${c.id}" ${draft.fixed.indexOf(c.id)===0?'disabled':''}>↑</button><button aria-label="下移${c.name}" data-legacy-down="${c.id}" ${draft.fixed.indexOf(c.id)===draft.fixed.length-1?'disabled':''}>↓</button></span>`:''}</div>`).join('');
 const recommendedGroups=[['体能',poolItems.filter(c=>c.type==='single')],['AI 跟练',poolItems.filter(c=>c.type==='ai')]].filter(([,items])=>items.length).map(([title,items])=>`<section class="legacy-content-group"><h4>${title}</h4>${items.map(c=>`<div class="legacy-content-name"><span class="legacy-pass">✓</span><b>${c.name}</b></div>`).join('')}</section>`).join('');
 const screenTypes=[['default','默认'],['rank','排行榜屏保'],['image','自定义图片屏保'],['video','运动视频屏保']];
 $('#admin-view').innerHTML=`<div class="legacy-admin-shell">
  <header class="legacy-admin-top"><div class="legacy-venue"><span class="legacy-home-icon">⌂</span><b>徐汇区新时代文明实践中心</b></div><div class="legacy-greeting">下午好，徐汇区新时代文明实践中心 <span class="legacy-menu">☰</span></div></header>
  <aside class="legacy-admin-side"><nav>
   <button><i class="legacy-icon blue">♙</i><span>数据统计</span><em>⌄</em></button>
   <button data-admin-section="heart"><i class="legacy-icon red">♥</i><span>心率数据</span><em>⌄</em></button>
   <button><i class="legacy-icon amber">▤</i><span>运动视频</span></button>
   <button><i class="legacy-icon green">◧</i><span>用户管理</span></button>
   <button><i class="legacy-icon mint">♙</i><span>账号管理</span></button>
   <button><i class="legacy-icon yellow">▣</i><span>我的账号</span></button>
   <button class="selected" data-admin-section="screen"><i class="legacy-icon purple">▰</i><span>屏保管理</span></button>
  </nav></aside>
  <main class="legacy-admin-main"><div class="legacy-page-heading"><h1>屏保管理</h1><button id="leave-admin">返回产品评审</button></div>
   <section class="legacy-config-card"><h2>请选择屏保类型</h2>
    <div class="legacy-screen-types">${screenTypes.map(([value,label])=>`<button class="legacy-radio ${(value==='video'&&isVideo)||(value==='image'&&!isVideo)?'checked':''}" data-screen-type="${value}"><i></i>${label}${value==='video'?'<small>v1.1 新增</small>':''}</button>`).join('')}</div>
    ${isVideo?`<div class="legacy-video-settings">
     <div class="legacy-section-title"><div><h3>运动视频屏保</h3><p>设备端全屏播放运动预览，并支持一键跟练、点击或左右滑动切换内容。</p></div><span class="legacy-new">新增</span></div>
     <div class="legacy-form-grid"><label>目标人群<select id="legacy-audience">${[['senior','康乐银发'],['adult','热力健将'],['youth','跃动少年']].map(([v,l])=>`<option value="${v}" ${draft.audience===v?'selected':''}>${l}</option>`).join('')}</select><small>用于筛选适合本人群的运动内容。</small></label><label>内容来源<select id="legacy-pool-mode"><option value="recommended" ${draft.poolMode==='recommended'?'selected':''}>按人群智能推荐</option><option value="fixed" ${draft.poolMode==='fixed'?'selected':''}>指定内容池</option></select><small>选择由系统智能推荐，或手动指定内容池。</small></label></div>
     <div class="legacy-subcard"><h3>${draft.poolMode==='fixed'?'指定内容池及播放顺序':'推荐内容预览'}</h3><p>${draft.poolMode==='fixed'?'勾选需要展示的运动，并用箭头调整轮播顺序。 ':`当前按所选人群生成预览；选择“指定内容池”后可编辑顺序。 `}${contentRule}</p>${draft.poolMode==='fixed'?`<div class="legacy-content-list">${fixedContentRows}</div>`:`<div class="legacy-content-groups">${recommendedGroups}</div>`}</div>
    </div>`:`<div class="legacy-image-settings"><div class="legacy-image-preview">${draft.images[0]?`<img src="${draft.images[0]}" alt="已上传屏保预览">`:'<img src="./assets/screensaver-fun-ai.jpg" alt="默认图片屏保预览">'}</div><div class="legacy-upload-line"><label class="legacy-upload-button">↥ 点击上传<input id="legacy-images-upload" type="file" accept="image/jpeg,image/png" multiple></label><span>请上传尺寸1440*2560，小于10M的JPG、PNG格式图片 <b>(${draft.images.length||1}/9)</b></span><button id="legacy-clear-images">恢复默认图片</button></div></div>`}
    <div id="admin-error" class="legacy-error" role="alert"></div>
   </section>
   <div class="legacy-actions"><button id="legacy-cancel">取消</button><button class="primary-save" id="save-config">保存</button></div>
  </main>
 </div>`;
 mountAdminReview();
 bindExistingAdmin();
}
function mountAdminReview(){const host=$('#admin-view'),shell=host.querySelector('.legacy-admin-shell'),page=requirementGroups[1].pages.find(([,title])=>title===(adminPage==='heart'?'心率数据':'屏保管理')),title=page[1],items=page[2],code=page[0];host.classList.add('admin-review-workspace');const stage=document.createElement('div');stage.className='admin-stage-area';const frame=document.createElement('div');frame.className='admin-preview-frame';stage.append(frame);frame.append(shell);host.prepend(stage);host.insertAdjacentHTML('beforeend',`<aside class="inspector admin-review-inspector"><div class="inspector-head"><span class="eyebrow">PAGE REVIEW</span><h2>本页需求与演示</h2><p><span>${code} ${title}</span><b>${items.length} 项变动</b></p></div><div class="control-group current-page-requirements"><h3>本页需求</h3><ul>${items.map(item=>`<li>${esc(item)}</li>`).join('')}</ul></div><div class="control-group"><h3>本页演示控制</h3>${adminPage==='screen'?'<div class="scenario-grid"><button data-admin-demo="video">运动视频配置</button><button data-admin-demo="image">图片配置</button></div><p class="admin-control-note">中间页面保留原有表单交互，可直接切换人群、推荐方式和内容顺序。</p>':'<p class="admin-control-note">当前展示心率数据无数据状态，本页无需额外模拟参数。</p>'}</div><div class="status-box"><span class="eyebrow">当前状态</span><p>${adminPage==='screen'?`屏保管理 · ${draft.mode==='video'?'运动视频屏保':'自定义图片屏保'}`:'心率数据 · 暂无配套设备数据'}</p></div></aside>`);document.querySelectorAll('[data-admin-page]').forEach(b=>b.classList.toggle('active',b.dataset.adminPage===adminPage));document.querySelectorAll('[data-admin-demo]').forEach(b=>b.onclick=()=>{draft.mode=b.dataset.adminDemo;renderExistingAdmin()})}
function rerenderExistingAdminAtScroll(focusSelector){const scroller=$('.admin-preview-frame')||$('.legacy-admin-shell'),scrollTop=scroller?.scrollTop||0;renderExistingAdmin();const nextScroller=$('.admin-preview-frame')||$('.legacy-admin-shell');if(nextScroller)nextScroller.scrollTop=scrollTop;if(focusSelector){const target=D.ownerDocument.querySelector(focusSelector);if(target)target.focus({preventScroll:true})}}
function bindExistingAdmin(){
 $('#leave-admin').onclick=()=>showView('device');const cancel=$('#legacy-cancel');if(cancel)cancel.onclick=()=>showView('device');
 document.querySelectorAll('[data-admin-section]').forEach(b=>b.onclick=()=>{adminPage=b.dataset.adminSection;renderExistingAdmin()});
 document.querySelectorAll('[data-screen-type]').forEach(b=>b.onclick=()=>{const type=b.dataset.screenType;if(type==='video'||type==='image'){draft.mode=type;renderExistingAdmin();return}toast(`${b.textContent.trim()}为现有功能，本轮仅展示入口`)});
 const pool=$('#legacy-pool-mode'),audience=$('#legacy-audience');if(pool)pool.onchange=e=>{draft.poolMode=e.target.value;rerenderExistingAdminAtScroll('#legacy-pool-mode')};if(audience)audience.onchange=e=>{draft.audience=e.target.value;rerenderExistingAdminAtScroll('#legacy-audience')};
 document.querySelectorAll('[data-legacy-pool]').forEach(b=>b.onchange=()=>{const id=b.dataset.legacyPool;draft.fixed=b.checked?[...draft.fixed,id]:draft.fixed.filter(item=>item!==id);rerenderExistingAdminAtScroll(`[data-legacy-pool="${id}"]`)});
 for(const dir of ['up','down'])document.querySelectorAll(`[data-legacy-${dir}]`).forEach(b=>b.onclick=()=>{const id=b.dataset[`legacy${dir[0].toUpperCase()+dir.slice(1)}`],i=draft.fixed.indexOf(id),j=i+(dir==='up'?-1:1);if(j>=0&&j<draft.fixed.length)[draft.fixed[i],draft.fixed[j]]=[draft.fixed[j],draft.fixed[i]];rerenderExistingAdminAtScroll(`[data-legacy-${dir}="${id}"]`)});
 const images=$('#legacy-images-upload');if(images)images.onchange=e=>{const files=[...e.target.files];if(files.length>9){$('#admin-error').textContent='最多上传 9 张图片，当前选择超过上限。';return}if(files.some(f=>!['image/jpeg','image/png'].includes(f.type)||f.size>10*1024*1024)){$('#admin-error').textContent='请上传小于 10M 的 JPG 或 PNG 图片。';return}imageURLs=files.map(f=>URL.createObjectURL(f));draft.images=[...imageURLs];renderExistingAdmin()};
 const clear=$('#legacy-clear-images');if(clear)clear.onclick=()=>{draft.images=[];renderExistingAdmin()};
 const save=$('#save-config');if(save)save.onclick=saveConfig;
}
function saveConfig(){const errors=[];if(!C.pool(draft).length)errors.push('内容池至少选择一项运动。');if(errors.length){$('#admin-error').textContent=errors.join(' ');return}config=structuredClone(draft);navigate(config.mode);showView('device');log('配置已保存，屏保已按新配置开始');toast('配置已保存到当前演示会话')}
function renderSpec(){const rows=[['两种屏保','后台单项选择屏保类型；设备端不跨类型切换','已确认'],['视频轮播','单项完整 3 遍；长课区间内随机 30 秒','已确认'],['启动身份','站位时登录／注册，绑定本次运动者','已确认'],['签到路径','舒缓热身操完成签到；普通运动完成自动签到','已确认'],['报告进度','单项体能、AI 跟练各加同款简短卡片','已确认'],['有效阈值','提前退出达到 10 秒即计为有效运动','已确认'],['里程碑档位','天数、千卡、分钟档位均为演示值','待评审'],['弱网人脸兜底','本地采集人脸并保存运动会话；联网后自动幂等补传','已确认'],['设备会话','首页／报告 60 秒超时，返回后清理当前身份','待评审']];$('#spec-view').innerHTML=`<div class="spec-layout"><h2>本轮评审看什么</h2><p>确认主流程是否顺畅，再讨论参数与异常。v1.1 尚未上线，原型内的示例数据不代表真实识别能力。</p><div class="spec-links"><a href="../../docs/requirements/v1.1-product-review.md" target="_blank">↗ 完整需求评审稿</a><a href="README.md" target="_blank">↗ Demo 运行与验证说明</a></div><div class="panel"><h3>从入口到积累</h3><p>屏保选运动 → 站位与身份确认 → 开始运动 → 符合规则后签到与累计 → 两类报告展示进度 → 查看独立里程碑。</p><table class="review-table"><thead><tr><th>模块</th><th>本稿口径</th><th>状态</th></tr></thead><tbody>${rows.map(([a,b,c])=>`<tr><td>${a}</td><td>${b}</td><td><span class="pill ${c==='已确认'?'':'pending'}">${c}</span></td></tr>`).join('')}</tbody></table></div><div class="panel"><h3>建议走查顺序</h3><p>① 分别从评审工具进入图片／视频屏保，检查设备端没有跨类型切换入口。<br>② 一键跟练，模拟老用户／新用户／人脸失败。<br>③ 分别在 9 秒和 10 秒提前结束，检查前者不计入、后者完成签到。<br>④ 同一天完成第二次运动，再重放报告，检查天数与累计。<br>⑤ 切另一用户、模拟下一天，再查看里程碑。<br>⑥ 客户后台切换推荐／指定内容池、调整顺序，再回设备验证。</p></div><div class="panel"><h3>本次未接入</h3><p>人脸与微信服务、真实注册、运动识别和计分、服务端结算、离线人脸采集与补传（本轮仅评审技术需求）、多设备并发、生产素材发布。AI 跟练预览区间、固定的舒缓热身操和视频素材由平台内部维护；默认静态色块与示例成绩均只用于交互评审。</p></div></div>`}
function renderDocs(){$('#docs-view').innerHTML=`<div class="docs-layout"><header class="docs-heading"><div><span class="eyebrow">REQUIREMENTS / V1.1</span><h2>本轮需求文档</h2><p>按使用终端归类，页面内只保留最终需求结论。</p></div><a href="../../docs/requirements/v1.1-product-review.md" target="_blank">查看完整评审稿 ↗</a></header>${requirementGroups.map(group=>`<section class="docs-platform"><div class="docs-platform-head"><span>${group.code}</span><div><h3>${group.title}</h3><p>${group.pages.length} 个页面 · ${group.pages.reduce((sum,page)=>sum+page[2].length,0)} 项需求</p></div></div><div class="docs-page-grid">${group.pages.map(([code,title,items])=>`<article><header><span>${code}</span><h4>${title}</h4><b>${items.length} 项</b></header><ul>${items.map(item=>`<li>${esc(item)}</li>`).join('')}</ul></article>`).join('')}</div></section>`).join('')}</div>`}
function resize(){const wrap=$('.device-wrap'),area=$('.stage-area');if(!wrap||!area||view!=='device')return;const noteSpace=requirementsOpen&&window.innerWidth>850?256:0,maxH=Math.max(560,window.innerHeight-192),w=Math.min(466,Math.max(240,area.clientWidth-55-noteSpace),maxH*9/16);wrap.style.width=w+'px';wrap.style.height=((w-14)*960/540+14)+'px';D.style.transform=`scale(${(w-14)/540})`}
$('#open-requirements').onclick=()=>{toggleRequirements(!requirementsOpen);if(requirementsOpen)$('#close-requirements').focus()};$('#close-requirements').onclick=()=>{toggleRequirements(false);$('#open-requirements').focus()};
document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>showView(b.dataset.view));document.querySelectorAll('[data-review-page]').forEach(b=>b.onclick=()=>{if(view!=='device')showView('device');openReviewPage(b.dataset.reviewPage)});document.querySelectorAll('[data-admin-page]').forEach(b=>b.onclick=()=>{adminPage=b.dataset.adminPage;showView('admin')});document.querySelectorAll('[data-milestone-metric]').forEach(b=>b.onclick=()=>changeMilestone(b.dataset.milestoneMetric,Number(b.dataset.step||0),b.dataset.zero==='true'));$('#checkin-unchecked').onclick=()=>setCheckinState(false);$('#checkin-checked').onclick=()=>setCheckinState(true);$('#speed').onchange=e=>{speed=+e.target.value;const v=D.querySelector('video');if(v)v.playbackRate=Math.min(16,speed);toast(`模拟时间速度 ×${speed}${v?'；真实视频最高 ×16':''}`)};$('#advance').onclick=()=>{for(let i=0;i<10;i++)tick(1,true);updateInspector()};$('#finish').onclick=()=>screen==='exercise'?finish('early'):toast('请先进入运动进行中页面');$('#next-day').onclick=()=>{dayOffset++;log('业务日期已前进一天（模拟）');if(screen==='milestones'||screen==='report'||screen==='home'||screen==='data')render();toast('已模拟下一天，下次运动可增加一天')};$('#replay').onclick=()=>{if(!lastReport){toast('请先完成一次运动');return}const result=C.settle(records,lastReport.record,config.threshold);records=result.records;persist();userId=lastReport.record.userId;navigate('report');log('重放同一 sessionId，累计保持不变')};$('#fail-video').onclick=()=>screen==='video'?failMedia():toast('请先进入视频屏保');$('#empty').onclick=()=>{screen='video';emptyOverride=true;activePool=[];preview=null;render();log('模拟内容池为空')};$('#reset').onclick=()=>{if(!confirm('清除本地模拟运动记录并恢复演示配置？'))return;records=[];milestoneDemo={};checkinDemo={};registered.delete('new');persist();lastReport=null;config=structuredClone(C.defaults);dayOffset=0;$('#person').value='chen';$('#identity').value='success';navigate('video');toast('模拟数据已重置')};D.addEventListener('pointerdown',()=>idle=0);D.addEventListener('keydown',()=>idle=0);window.addEventListener('resize',resize);document.addEventListener('visibilitychange',()=>{const v=D.querySelector('video');if(v){if(document.hidden)v.pause();else if(view==='device')v.play().catch(()=>{})}});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&requirementsOpen){toggleRequirements(false);$('#open-requirements').focus()}});
D.addEventListener('keydown',e=>{if(e.key==='Escape'&&calendarOpen){calendarOpen=false;render();D.querySelector('#checkin').focus()}});
let lastTick=performance.now();setInterval(()=>{const currentTime=performance.now(),dt=Math.min(.5,(currentTime-lastTick)/1000);lastTick=currentTime;tick(dt*speed);if(!document.hidden&&view==='device'){idle+=dt;if((screen==='home'||screen==='report'||(screen==='data'&&!dataMobile))&&idle>=config.idle){navigate(config.mode);log('无操作超时，已清理当前个人会话并回屏保')}}},100);
// Pointer gestures complement the explicit previous/next controls.
let swipe=null,suppressSwipeClickUntil=0;
D.addEventListener('pointerdown',e=>{
 if(screen!=='video'||!preview||activePool.length<2||!e.isPrimary||e.button!==0||e.target.closest('button,a,input,select'))return;
 swipe={id:e.pointerId,x:e.clientX,y:e.clientY,epoch:mediaEpoch};
 D.setPointerCapture(e.pointerId);
});
D.addEventListener('pointerup',e=>{
 if(!swipe||e.pointerId!==swipe.id)return;
 const start=swipe;swipe=null;
 if(D.hasPointerCapture(e.pointerId))D.releasePointerCapture(e.pointerId);
 const dx=e.clientX-start.x,dy=e.clientY-start.y;
 const threshold=Math.max(32,D.getBoundingClientRect().width*.12);
 if(screen==='video'&&mediaEpoch===start.epoch&&Math.abs(dx)>=threshold&&Math.abs(dx)>Math.abs(dy)*1.5){
  suppressSwipeClickUntil=performance.now()+400;nextItem(dx<0?1:-1);
 }
});
D.addEventListener('pointercancel',()=>swipe=null);
D.addEventListener('lostpointercapture',()=>swipe=null);
D.addEventListener('click',e=>{if(performance.now()<suppressSwipeClickUntil){e.preventDefault();e.stopImmediatePropagation()}},true);

// Read-only review state is also used by deterministic browser checks.
window.reviewState=()=>({screen,view,userId,course:chosen?.id,previewCourse:current()?.id,previewTime,cycles,elapsed,recordCount:records.length,records:structuredClone(records),totals:C.totals(records,userId),lastReport:structuredClone(lastReport),config:structuredClone(config)});
$('#identity').onchange=()=>{if(screen==='guide')scheduleFace()};$('#person').onchange=()=>{if(screen==='guide'){scheduleFace();return}if(screen==='home'||screen==='data'||screen==='milestones'){userId=$('#person').value;authState='confirmed';render()}};
initPreview();

})();
